# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Desktop\CAPSTONE\RTHM-Device\FRONTEND\newScannertry.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(639, 350)
        Dialog.setStyleSheet("QDialog#Dialog{\n"
"background-color:qlineargradient(spread:pad, x1:0.005, y1:0, x2:1, y2:1, stop:0 rgba(200, 197, 191, 255), stop:1 rgba(255, 255, 255, 255))}")
        self.lblOxygenLevel = QtWidgets.QLabel(Dialog)
        self.lblOxygenLevel.setGeometry(QtCore.QRect(190, 220, 61, 31))
        self.lblOxygenLevel.setStyleSheet("color: #594646;")
        self.lblOxygenLevel.setObjectName("lblOxygenLevel")
        self.lblHeartRate = QtWidgets.QLabel(Dialog)
        self.lblHeartRate.setGeometry(QtCore.QRect(190, 170, 61, 31))
        self.lblHeartRate.setStyleSheet("color: #594646;")
        self.lblHeartRate.setObjectName("lblHeartRate")
        self.lblRoomTemp = QtWidgets.QLabel(Dialog)
        self.lblRoomTemp.setGeometry(QtCore.QRect(430, 220, 61, 31))
        self.lblRoomTemp.setStyleSheet("color: #594646;")
        self.lblRoomTemp.setObjectName("lblRoomTemp")
        self.lblBodyTemp = QtWidgets.QLabel(Dialog)
        self.lblBodyTemp.setGeometry(QtCore.QRect(426, 170, 61, 31))
        self.lblBodyTemp.setStyleSheet("color: #594646;")
        self.lblBodyTemp.setObjectName("lblBodyTemp")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lblOxygenLevel.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Null</span></p></body></html>"))
        self.lblHeartRate.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Null</span></p></body></html>"))
        self.lblRoomTemp.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Null</span></p></body></html>"))
        self.lblBodyTemp.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Null</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
