# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InputRecepient.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnBack = QtWidgets.QLabel(self.centralwidget)
        self.btnBack.setGeometry(QtCore.QRect(-20, -11, 181, 81))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.btnBack.setFont(font)
        self.btnBack.setStyleSheet("background-color: rgb(255, 102, 0);\n"
"background-color: rgb(255, 226, 206);\n"
"border-radius:20px;")
        self.btnBack.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.btnBack.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.btnBack.setObjectName("btnBack")
        self.lblName = QtWidgets.QLabel(self.centralwidget)
        self.lblName.setGeometry(QtCore.QRect(880, 0, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.lblName.setFont(font)
        self.lblName.setStyleSheet("border-radius:20px;")
        self.lblName.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lblName.setAlignment(QtCore.Qt.AlignCenter)
        self.lblName.setObjectName("lblName")
        self.btnDelete = QtWidgets.QLabel(self.centralwidget)
        self.btnDelete.setGeometry(QtCore.QRect(-20, 480, 151, 111))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btnDelete.setFont(font)
        self.btnDelete.setStyleSheet("background-color: rgb(255, 102, 0);\n"
"background-color: rgb(255, 226, 206);\n"
"border-radius:20px;")
        self.btnDelete.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.btnDelete.setText("")
        self.btnDelete.setPixmap(QtGui.QPixmap("images/delete3.png"))
        self.btnDelete.setAlignment(QtCore.Qt.AlignCenter)
        self.btnDelete.setObjectName("btnDelete")
        self.btnSend = QtWidgets.QLabel(self.centralwidget)
        self.btnSend.setGeometry(QtCore.QRect(890, 480, 151, 111))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btnSend.setFont(font)
        self.btnSend.setStyleSheet("background-color: rgb(255, 102, 0);\n"
"background-color: rgb(255, 226, 206);\n"
"border-radius:20px;")
        self.btnSend.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.btnSend.setText("")
        self.btnSend.setPixmap(QtGui.QPixmap("images/send3.png"))
        self.btnSend.setAlignment(QtCore.Qt.AlignCenter)
        self.btnSend.setObjectName("btnSend")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(120, 90, 781, 331))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: #E5E5E5;\n"
"border-radius:30px;")
        self.label_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.lblInput = QtWidgets.QLabel(self.centralwidget)
        self.lblInput.setGeometry(QtCore.QRect(120, 130, 781, 100))
        font = QtGui.QFont()
        font.setPointSize(38)
        font.setBold(True)
        font.setWeight(75)
        self.lblInput.setFont(font)
        self.lblInput.setAlignment(QtCore.Qt.AlignCenter)
        self.lblInput.setObjectName("lblInput")
        self.txtInputName = QtWidgets.QTextEdit(self.centralwidget)
        self.txtInputName.setGeometry(QtCore.QRect(202, 270, 621, 70))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.txtInputName.setFont(font)
        self.txtInputName.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.txtInputName.setStyleSheet("font-size: 26;")
        self.txtInputName.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtInputName.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtInputName.setObjectName("txtInputName")
        self.lblBackground = QtWidgets.QLabel(self.centralwidget)
        self.lblBackground.setGeometry(QtCore.QRect(0, 0, 1024, 600))
        self.lblBackground.setStyleSheet("background-color: #ffffff;")
        self.lblBackground.setText("")
        self.lblBackground.setObjectName("lblBackground")
        self.lblBack = QtWidgets.QLabel(self.centralwidget)
        self.lblBack.setGeometry(QtCore.QRect(10, 13, 35, 35))
        self.lblBack.setText("")
        self.lblBack.setPixmap(QtGui.QPixmap("images/angle-left2.png"))
        self.lblBack.setObjectName("lblBack")
        self.lblBackground.raise_()
        self.btnBack.raise_()
        self.lblName.raise_()
        self.btnDelete.raise_()
        self.btnSend.raise_()
        self.label_3.raise_()
        self.lblInput.raise_()
        self.txtInputName.raise_()
        self.lblBack.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnBack.setText(_translate("MainWindow", "Back  "))
        self.lblName.setText(_translate("MainWindow", "Renj"))
        self.lblInput.setText(_translate("MainWindow", "Input Recepient"))
        self.txtInputName.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:26pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
